const listTrails = [
    {
        "municipality": "Nordreisa",
        "area": "Reisadalen",
        "name": "Gahperus",
        "route": "Gahperus",
        "description": "Et av de desidert beste områdene for de som er glad høydemeter, men vil komme seg opp relativt kjapt. Her er det grusvei helt til toppen, og mange ruter man kan ta ned fjellet.",
        "turbeskrivelse": "",
        "type": "Enduro",
        "grade": "blue",
        "water": "Elv",
        "severalRoutes": "Ja",
        "surface": "Morene, grusvei, steinete sti, ATV-spor, skogssti",
        "hikingTrail": "Nei",
        "parking": "69.5394, 21.3321",
        "time": "Kvart dag",
        "tags": ""
    },
    {
        "municipality": "Nordreisa",
        "area": "Reisadalen",
        "name": "Puntadalen",
        "route": "Puntadalen",
        "description": "En fin ettermiddagstur langs veien gjennom Puntadalen. Turen er like fin opp som ned, med bakker, bekker, og mye flatt terreng langs en gammel skogsvei. Den kan følges opp til  Ørretvannet, Saravann, Sarafossen, eller helt til Somas.",
        "turbeskrivelse": "",
        "type": "XC",
        "grade": "green",
        "water": "Bekk, vann",
        "severalRoutes": "Ja",
        "surface": "Skogsvei, ATV-spor, sti",
        "hikingTrail": "Ja",
        "parking": "69.4975, 21.4341",
        "time": "Kvart dag",
        "tags": "Tursti"
    },
    {
        "municipality": "Nordreisa",
        "area": "Straumfjorden",
        "name": "Reašvárri",
        "route": "Reašvárri",
        "description": "Stien ned Reašvárri er teknisk, men morsom hvis man holder hode kaldt. Halvveis ned fjellet går det over til ATV-spor, så derfra kan man gi full gass ned til fylkesveien.",
        "turbeskrivelse": "",
        "type": "Enduro",
        "grade": "blue",
        "water": "Bekk",
        "severalRoutes": "Ja",
        "surface": "Steinete sti, fast skogsvei",
        "hikingTrail": "Ja",
        "parking": "69.8411, 21.1446",
        "time": "Halve dagen",
        "tags": "Tursti Beitemark"
    },
    {
        "municipality": "Nordreisa",
        "area": "Storslett",
        "name": "Nordkjosfjellet",
        "route": "Nordkjosfjellet",
        "description": "En klassiker for de som liker stisykling ned fjell. Mye morsomme berg helt fra start, og en fin payoff med breiere sti på siste halvdel hvor farta kan være høyere.",
        "turbeskrivelse": "",
        "type": "Enduro",
        "grade": "green",
        "water": "Bekk",
        "severalRoutes": "Nei",
        "surface": "Berggrunn, løs sti, myrsti, ATV-spor",
        "hikingTrail": "Ja",
        "parking": "69.7931, 21.0522",
        "time": "Kvart dag",
        "tags": "Tursti"
    },
    {
        "municipality": "Nordreisa",
        "area": "Reisadalen",
        "name": "Lintuvaara",
        "route": "Lintuvaara",
        "description": "Utrolig fint lite område i Reisadalen, som egentlig er en labyrint av stier og gamle veier. Hovedruta går tvers gjennom naturreservatet med lite høydemeter. En fin tur som kan kobles opp mot flere andre stier i området.",
        "turbeskrivelse": "",
        "type": "XC",
        "grade": "white",
        "water": "Nei",
        "severalRoutes": "Ja",
        "surface": "Grusvei, skogsvei, ATV-spor",
        "hikingTrail": "Nei",
        "parking": "",
        "time": "Kvart dag",
        "tags": "Naturreservat"
    },
    {
        "municipality": "Nordreisa",
        "area": "Reisadalen",
        "name": "Vinnelys",
        "route": "Vinnelys",
        "description": "Gamleveien på østsiden av Reisadalen passer fint til treningsøkta. Her er det grusvei nesten hele veien og mange muligheter for de som vil utforske litt.",
        "turbeskrivelse": "",
        "type": "XC",
        "grade": "white",
        "water": "Elv",
        "severalRoutes": "Ja",
        "surface": "Grusvei og steinete skogsvei",
        "hikingTrail": "Nei",
        "parking": "69.5198, 21.3922",
        "time": "Kvart dag",
        "tags": "Beitemark"
    },
    {
        "municipality": "Nordreisa",
        "area": "Reisadalen",
        "name": "Langmyrfjellet",
        "route": "Langmyrfjellet",
        "description": "Alt! Hopp, fart, grus, gjørme, stein, berg, myr, utsikt og det som måtte være får du ned Langmyrfjellet. Definitivt en av favorittene.",
        "turbeskrivelse": "",
        "type": "Enduro",
        "grade": "green",
        "water": "Ja",
        "severalRoutes": "Ja",
        "surface": "Grusvei, skogsvei, myrsti, berg, steinur, noen glatte partier",
        "hikingTrail": "Nei",
        "parking": "69.5198, 21.3922",
        "time": "Halve dagen",
        "tags": "Beitemark"
    },
    {
        "municipality": "Nordreisa",
        "area": "Oksfjorddalen",
        "name": "Luovosskáidi",
        "route": "Luovosskáidi",
        "description": "Historisk og fint område i Oksfjorddalen som er verdt turen. Slakt på toppen, før det går beint ned sikk-sakk veien til Vaddas, så fin grusvei ned til bommen.",
        "turbeskrivelse": "",
        "type": "XC",
        "grade": "green",
        "water": "Elv",
        "severalRoutes": "Nei",
        "surface": "Grusvei",
        "hikingTrail": "Nei",
        "parking": "69.8248, 21.4497",
        "time": "Kvart dag",
        "tags": "Beitemark"
    },
    {
        "municipality": "Nordreisa",
        "area": "Storslett",
        "name": "Báiskitvarden",
        "route": "Báiskitvarden",
        "description": "Klassiker med en flott sti ned fjellet. Flere litt krevende partier, og siste del er ganske bratt på en steinete sti (OBS: Ruta på kartet er feil på siste del, da jeg var litt for nysgjerrig).",
        "turbeskrivelse": "",
        "type": "Enduro",
        "grade": "blue",
        "water": "Vann",
        "severalRoutes": "Ja",
        "surface": "Steinete sti, røtter",
        "hikingTrail": "Ja",
        "parking": "69.7642, 21.0651",
        "time": "Kvart dag",
        "tags": "Tursti"
    },
    {
        "municipality": "Nordreisa",
        "area": "Bakkeby",
        "name": "Gjøvarden",
        "route": "Gjøvarden",
        "description": "Med en start hvor det er utsikt mot både Kågen og innover Reisafjorden, er det allere en god grunn for å ta turen til Gjøvarden. Stien ned fra toppen er tydelig og god med lite steiner. Det er ett vanskelig parti, som 99 prosent av oss nok vil trille sykkelen ned.",
        "turbeskrivelse": "",
        "type": "Enduro",
        "grade": "green",
        "water": "Bekk",
        "severalRoutes": "Ja",
        "surface": "Fast sti, steinete sti, røtter",
        "hikingTrail": "Ja",
        "parking": "69.8877, 20.9220",
        "time": "Kvart dag",
        "tags": "Beitemark"
    },
    {
        "municipality": "Nordreisa",
        "area": "Storslett",
        "name": "Utsikten",
        "route": "Utsikten",
        "description": "Tilgjengelig og artig sti som passer for alt fra nybegynnere til viderekomne. Her kan man holde høyt tempo fra start til slutt, eller bare trille rolig ned den flotte stien.",
        "turbeskrivelse": "",
        "type": "Enduro",
        "grade": "green",
        "water": "Elv, bekk",
        "severalRoutes": "Ja",
        "surface": "Fast sti, løse partier, gress",
        "hikingTrail": "Ja",
        "parking": "69.7553, 21.0222",
        "time": "Fort gjort",
        "tags": "Tursti"
    },
    {
        "municipality": "Nordreisa",
        "area": "Straumfjorden",
        "name": "Fosselvfossen",
        "route": "Fosselvfossen",
        "description": "Kjapt opp og kjapt ned. Det er et lite parti hvor det er trangt mellom trerne, men ellers kan man holde grei fart.",
        "turbeskrivelse": "",
        "type": "Enduro",
        "grade": "green",
        "water": "Elv",
        "severalRoutes": "Ja",
        "surface": "Fast sti, steiner, røtter, skogsvei",
        "hikingTrail": "Ja",
        "parking": "69.8397, 21.2107",
        "time": "Fort gjort",
        "tags": "Tursti Beitemark"
    },
    {
        "municipality": "Nordreisa",
        "area": "Sørkjosen",
        "name": "Truisku",
        "route": "Truisku",
        "description": "Veldig populært turmål som man fint kan sykle ned, men helst på tidspunkt hvor færre besøker Truisku og sherpatrappa.",
        "turbeskrivelse": "",
        "type": "Enduro",
        "grade": "green",
        "water": "Elv",
        "severalRoutes": "Ja",
        "surface": "Fast sti, steiner, røtter, skogsvei",
        "hikingTrail": "Ja",
        "parking": "69.7863, 20.9476",
        "time": "Fort gjort",
        "tags": "Tursti"
    },
    {
        "municipality": "Nordreisa",
        "area": "Rotsund",
        "name": "Storbakklia",
        "route": "Storbakklia",
        "description": "Morsom tur fra Sikkájárvi til Rotsunddalen. Ruta følger en gammel ATV-vei, men det er flere ruter ned. Enkelte partier under tregrensa er litt gjengrodd.",
        "turbeskrivelse": "",
        "type": "Enduro",
        "grade": "blue",
        "water": "Bekk",
        "severalRoutes": "Ja",
        "surface": "ATV-spor, fast sti, steiner, grusvei",
        "hikingTrail": "Ja",
        "parking": "69.7678, 20.7317",
        "time": "Kvart dag",
        "tags": "Tursti Beitemark"
    },
    {
        "municipality": "Nordreisa",
        "area": "Reisadalen",
        "name": "Moskodalen",
        "route": "Moskodalen",
        "description": "Ned fra gruvene i Moskodalen må man nok gå av sykkelen et par gangen, men det er en fin tur å ta en ettermiddag. Fra Gapahuken og ned går det merkelig fort langs skogsveien.",
        "turbeskrivelse": "",
        "type": "XC",
        "grade": "white",
        "water": "Elv",
        "severalRoutes": "Nei",
        "surface": "Skogsvei, sti, steinur",
        "hikingTrail": "Ja",
        "parking": "69.70682, 21.27003",
        "time": "Halve dagen",
        "tags": "Tursti"
    },
    {
        "municipality": "Nordreisa",
        "area": "Storslett",
        "name": "Jyppyrä",
        "route": "Jyppyrä",
        "description": "Fire kilometer hvor man får litt av hvert. Rask og grei sti i starten. Fra foten av Jyppyrä og ned til tregrensa følger man en steinete sti, og avslutter med nydelig stisykling helt til det flater ut.",
        "turbeskrivelse": "",
        "type": "Enduro",
        "grade": "red",
        "water": "Bekk",
        "severalRoutes": "Ja",
        "surface": "Skogsvei, sti, røtter",
        "hikingTrail": "Ja",
        "parking": "69.76424271564689, 21.06507179191515",
        "time": "Halve dagen",
        "tags": "Tursti Beitemark"
    },
    {
        "municipality": "Nordreisa",
        "area": "Reisadalen",
        "name": "Sarafossen",
        "route": "Sarafossen",
        "description": "Enten man går opp for å se på Sarafossen eller bare vil sykle, er det her en helt grei tur. Svært bra første halvdel med fin og enkel stisykling. De siste høydemeterne er det en del steiner.",
        "turbeskrivelse": "",
        "type": "Enduro",
        "grade": "green",
        "water": "Elv, bekk",
        "severalRoutes": "Ja",
        "surface": "Sti, mye steiner og røtter, skogsvei",
        "hikingTrail": "Ja",
        "parking": "69.7863, 20.9476",
        "time": "Fort gjort",
        "tags": "Tursti"
    },
    {
        "municipality": "Nordreisa",
        "area": "Sørkjosen",
        "name": "Brattlia",
        "route": "Brattlia",
        "description": "Skal du inn til Sikka, er dette en helt grei tur. Svært fint i øvre del av Jernelvdalen. Første del ned er overraskende gøy, men midtveis og mot slutten er det veldig steinete.",
        "turbeskrivelse": "",
        "type": "Enduro",
        "grade": "blue",
        "water": "Vann",
        "severalRoutes": "Nei",
        "surface": "Fjellsti, veldig steinete sti",
        "hikingTrail": "Ja",
        "parking": "69.4727, 21.48772",
        "time": "Fort gjort",
        "tags": "Tursti"
    },
    {
        "municipality": "Nordreisa",
        "area": "Rotsund",
        "name": "Pilteridalen",
        "route": "Pilteridalen",
        "description": "Helt grei tur inn til gammen i Pilteridalen. Mye stein og hull på stien som man vil merke på tur opp.",
        "turbeskrivelse": "",
        "type": "XC",
        "grade": "green",
        "water": "Elv",
        "severalRoutes": "Nei",
        "surface": "Traktorvei, veldig steinete sti",
        "hikingTrail": "Ja",
        "parking": "69.75134, 20.73557",
        "time": "Kvart dag",
        "tags": "Tursti"
    },
    {
        "municipality": "Nordreisa",
        "area": "Reisadalen",
        "name": "Saraelv",
        "route": "Saraelv",
        "description": "Nedoverbakke nesten hele veien med få krevende partier. Det er litt stein her og der, men med litt planlegging på tur opp har man god flyt hele veien ned.",
        "turbeskrivelse": "",
        "type": "Enduro",
        "grade": "green",
        "water": "Bell",
        "severalRoutes": "Ja",
        "surface": "ATV-spor, sti, røtter og steiner",
        "hikingTrail": "Ja",
        "parking": "69.45012, 21.53775731",
        "time": "Kvart dag",
        "tags": "Tursti"
    },
    {
        "municipality": "Nordreisa",
        "area": "Storslett",
        "name": "Kvennes",
        "route": "Kvennes",
        "description": "Stier og veier i alle retninger med lite høydemeter. Passer fint for en trimtur og for nybegynnere som vil bli kjent med sykkelen.",
        "turbeskrivelse": "",
        "type": "XC",
        "grade": "white",
        "water": "Nei",
        "severalRoutes": "Ja",
        "surface": "Sti, grusvei",
        "hikingTrail": "Ja",
        "parking": "69.782433, 21.035587",
        "time": "Fort gjort",
        "tags": "Tursti Naturreservat"
    },
    {
        "municipality": "Nordreisa",
        "area": "Oksfjorddalen",
        "name": "Riehppegáisá",
        "route": "Riehppegáisá",
        "description": "Fra skulderen av Riehppegáisá følger man en gammel gruvevei ned til Vaddas. Nydelig natur! Bratt og nye stein sikksakk ned fjellsia, så god flyt ned til dalen, så opp og ned langs Storelidalen, og slutter med et raskt parti til Vaddas.",
        "turbeskrivelse": "",
        "type": "Enduro",
        "grade": "blue",
        "water": "Elv",
        "severalRoutes": "Nei",
        "surface": "ATV-spor, stein, reinsti",
        "hikingTrail": "Nei",
        "parking": "69.81166, 21.59379",
        "time": "Dagstur",
        "tags": "Beitemark"
    },
    {
        "municipality": "Nordreisa",
        "area": "Storslett",
        "name": "Lånivannet",
        "route": "Lånivannet",
        "description": "Kort, men veldig teknisk. Har flere bratte parti hvor man får testet både ferdighetene sine og sykkelen. Husk knebeskyttere!",
        "turbeskrivelse": "",
        "type": "Enduro",
        "grade": "black",
        "water": "Bekk, vann",
        "severalRoutes": "Nei",
        "surface": "Traktorvei, sti, berg, røtter",
        "hikingTrail": "Ja",
        "parking": "69.73662, 21.12021",
        "time": "Fort gjort",
        "tags": "Tursti"
    },
    {
        "municipality": "Nordreisa",
        "area": "Storslett",
        "name": "Beassejávrrit",
        "route": "Beassejávrrit",
        "description": "Enkel tur som kan være grei for å trene på litt brattere stisykling. Det er to vanskelig og steine parti, men ellers er stien veldig god.",
        "turbeskrivelse": "",
        "type": "Enduro",
        "grade": "green",
        "water": "Bekk, vann",
        "severalRoutes": "Nei",
        "surface": "Sti, steiner, røtter",
        "hikingTrail": "Ja",
        "parking": "69.7553, 21.0222",
        "time": "Kvart dag",
        "tags": "Tursti"
    },
    {
        "municipality": "Nordreisa",
        "area": "Bakkeby",
        "name": "Sokkelvika",
        "route": "Sokkelvika",
        "description": "Morsom trimtur. Grei, men stedvis utrydelig sti ned til Bakkeby. Bratt opp Latterfjellet, morsomt og utfordrende ned. Start kan være ved havna i Sørkjosen eller ved Veibrink. Obs! Syklet ruta litt feil, så havnet i hagen til noen i Bakkeby.",
        "turbeskrivelse": "",
        "grade": "blue",
        "water": "Bekk, vann",
        "severalRoutes": "Ja",
        "surface": "Sti, steiner, røtter",
        "hikingTrail": "Ja",
        "parking": "69.8174, 20.8647",
        "time": "Kvart dag",
        "tags": "Tursti Beitemark"
    }
];

export { listTrails };